SELECT 
T.TRANSPORTMACHINENAME 
, ROUND(AVG(TO_NUMBER((T.TRANSFERRINGTIME-T.CREATEDTIME)*24*60*60)),0) WAITTIME
, ROUND(AVG(TO_NUMBER((T.COMPLETEDTIME-T.TRANSFERRINGTIME)*24*60*60)),0) TRANSTIME
--, ROUND(AVG(T.ELAPSED / 1000),0) ALLTIME 
, ROUND(COUNT(*),0) CC
FROM mcsadm.NT_S_TRANSPORTCMDDETAIL T
WHERE 
    --T.TRANSPORTMACHINENAME = '3TSTK01' AND 
    T.FROMBAYNAME = 'TP_2F' AND
    T.CREATEDTIME > '16-9月 -21' AND
    T.CREATEDTIME < '23-9月 -21' AND
    T.ABORTEDTIME IS NULL AND T.CANCELEDTIME IS NULL AND T.TERMINATEDTIME IS NULL
GROUP BY T.TRANSPORTMACHINENAME
ORDER BY 1
; 

SELECT T.TRANSPORTMACHINENAME, COUNT(*) 
FROM NT_S_TRANSPORTCMDDETAIL T
WHERE 
    --T.TRANSPORTMACHINENAME = '3TSTK01' AND 
    T.FROMBAYNAME = 'TP_2F' AND
    T.CREATEDTIME > '14-1月 -21' AND
    T.CREATEDTIME < '21-1月 -21' AND
    T.ABORTEDTIME IS NULL AND T.CANCELEDTIME IS NULL AND T.TERMINATEDTIME IS NULL
GROUP BY T.TRANSPORTMACHINENAME
ORDER BY 1
;